# Generated by Django 5.2.12 on 2026-03-24 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='勇者', max_length=50, verbose_name='プレイヤー名')),
                ('level', models.IntegerField(default=1, verbose_name='レベル')),
                ('current_exp', models.IntegerField(default=0, verbose_name='現在EXP')),
                ('max_exp', models.IntegerField(default=100, verbose_name='最大EXP')),
                ('allocatable_points', models.IntegerField(default=0, verbose_name='割り振りポイント')),
                ('gender', models.CharField(choices=[('f', '女性'), ('m', '男性')], default='f', max_length=1, verbose_name='性別')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
            ],
            options={
                'verbose_name': 'プレイヤー',
                'verbose_name_plural': 'プレイヤー',
            },
        ),
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='習慣名')),
                ('category', models.CharField(choices=[('運動', '運動'), ('学習', '学習'), ('健康', '健康'), ('メンタル', 'メンタル')], default='運動', max_length=20, verbose_name='カテゴリ')),
                ('order', models.IntegerField(default=0, verbose_name='表示順')),
                ('streak', models.IntegerField(default=0, verbose_name='現在の連続日数')),
                ('best_streak', models.IntegerField(default=0, verbose_name='最長連続日数')),
                ('total_count', models.IntegerField(default=0, verbose_name='累計カウント')),
                ('total_exp', models.IntegerField(default=0, verbose_name='累計EXP')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='作成日')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habits', to='api.playerprofile', verbose_name='プレイヤー')),
            ],
            options={
                'verbose_name': '習慣',
                'verbose_name_plural': '習慣',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='HabitLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日付')),
                ('count', models.IntegerField(default=0, verbose_name='カウント数')),
                ('exp_gained', models.IntegerField(default=0, verbose_name='獲得EXP')),
                ('habit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='api.habit', verbose_name='習慣')),
            ],
            options={
                'verbose_name': '習慣ログ',
                'verbose_name_plural': '習慣ログ',
                'ordering': ['-date'],
                'unique_together': {('habit', 'date')},
            },
        ),
        migrations.CreateModel(
            name='CharacterStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('運動力', '運動力'), ('学習力', '学習力'), ('精神力', '精神力'), ('健康力', '健康力')], max_length=20, verbose_name='ステータス名')),
                ('level', models.IntegerField(default=1, verbose_name='レベル')),
                ('current_exp', models.IntegerField(default=0, verbose_name='現在EXP')),
                ('max_exp', models.IntegerField(default=100, verbose_name='最大EXP')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='api.playerprofile', verbose_name='プレイヤー')),
            ],
            options={
                'verbose_name': 'キャラクターステータス',
                'verbose_name_plural': 'キャラクターステータス',
                'unique_together': {('player', 'name')},
            },
        ),
    ]
