# Generated by Django 4.2.29 on 2026-04-06 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_passkey'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='pendingchallenge',
            new_name='api_pending_key_dd2386_idx',
            old_name='api_pending_key_idx',
        ),
        migrations.AlterField(
            model_name='magiclinktoken',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='passkeycredential',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='pendingchallenge',
            name='data',
            field=models.JSONField(default=dict, verbose_name='付属データ (email, name 等)'),
        ),
        migrations.AlterField(
            model_name='pendingchallenge',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
