# Generated by Django 4.2.30 on 2026-04-18 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_habit_reset_cycle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playergachastatus',
            name='daily_last_granted',
            field=models.DateField(blank=True, null=True, verbose_name='最終デイリー付与日'),
        ),
    ]
