# Generated by Django 4.2.30 on 2026-04-25 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_habit_category_no_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notif_type',
            field=models.CharField(choices=[('friend_request', 'フレンド申請'), ('message', 'メッセージ'), ('level_up', 'レベルアップ'), ('streak_alert', 'ストリーク危機'), ('title_unlocked', '称号解除'), ('gift', 'ギフト'), ('quest', 'クエスト'), ('achievement', '実績解除')], max_length=20, verbose_name='通知種別'),
        ),
        migrations.AlterField(
            model_name='playerachievement',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
