# Generated by Django 4.2.30 on 2026-05-01 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_gacha01_duplicate_reward'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gachareward',
            name='reward_type',
            field=models.CharField(choices=[('exp', '経験値'), ('diamond', 'ダイヤ'), ('xp_boost', 'XPブースト'), ('title', '称号'), ('character', 'キャラクター')], max_length=20, verbose_name='報酬種別'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='habit_type',
            field=models.CharField(choices=[('count', 'カウント'), ('checklist', 'チェックリスト'), ('todo', 'ToDo')], default='count', max_length=20, verbose_name='タイプ'),
        ),
    ]
