# Generated by Django 4.2.30 on 2026-05-02 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_character_image_path_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='image_path',
            field=models.CharField(help_text='識別子のみ（例: normal_1, archer）。Flutter は assets/images/characters/character_{identifier}.png に解決する。', max_length=100, verbose_name='画像パス'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notif_type',
            field=models.CharField(choices=[('friend_request', 'フレンド申請'), ('friend_accepted', 'フレンド成立'), ('message', 'メッセージ'), ('level_up', 'レベルアップ'), ('streak_alert', 'ストリーク危機'), ('title_unlocked', '称号解除'), ('gift', 'ギフト'), ('quest', 'クエスト'), ('achievement', '実績解除')], max_length=20, verbose_name='通知種別'),
        ),
    ]
