# Generated by Django 4.2.30 on 2026-05-02 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_alter_character_image_path_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimelineEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='タイトル')),
                ('date', models.DateField(verbose_name='日付')),
                ('start_time', models.TimeField(verbose_name='開始時刻')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='終了時刻')),
                ('category', models.CharField(choices=[('habit', '習慣'), ('health', '健康'), ('work', '作業'), ('rest', '休憩'), ('social', '交流'), ('other', 'その他')], default='other', max_length=20, verbose_name='カテゴリ')),
                ('icon_key', models.CharField(choices=[('wb_sunny', '朝・起床'), ('restaurant', '食事'), ('directions_run', '運動'), ('menu_book', '学習'), ('self_improvement', '瞑想・休憩'), ('groups', '社交'), ('work', '作業'), ('bedtime', '就寝'), ('event', 'その他')], default='event', max_length=50, verbose_name='アイコンキー')),
                ('is_completed', models.BooleanField(default=False, verbose_name='完了')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('habit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timeline_events', to='api.habit', verbose_name='紐付け習慣')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_events', to='api.playerprofile', verbose_name='プレイヤー')),
            ],
            options={
                'verbose_name': 'タイムラインイベント',
                'ordering': ['date', 'start_time'],
            },
        ),
    ]
