# Generated by Django 5.2.12 on 2026-05-05 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0048_magiclinktoken_purpose'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='habitrewardlog',
            new_name='api_habitre_player__ec2dbe_idx',
            old_name='api_habitrew_player_idx',
        ),
        migrations.RenameIndex(
            model_name='habitrewardlog',
            new_name='api_habitre_habit_i_1a65e8_idx',
            old_name='api_habitrew_habit_idx',
        ),
        migrations.RenameIndex(
            model_name='socialaccount',
            new_name='api_sociala_provide_18019b_idx',
            old_name='api_social_provider_idx',
        ),
        migrations.AddField(
            model_name='timelineevent',
            name='external_id',
            field=models.CharField(blank=True, default='', help_text='外部カレンダーのイベント ID（重複インポート防止）', max_length=500, verbose_name='外部イベントID'),
        ),
        migrations.AddField(
            model_name='timelineevent',
            name='source',
            field=models.CharField(choices=[('local', 'ローカル'), ('google', 'Google カレンダー'), ('apple', 'Apple カレンダー')], default='local', max_length=20, verbose_name='発生源'),
        ),
        migrations.AddConstraint(
            model_name='timelineevent',
            constraint=models.UniqueConstraint(condition=models.Q(('external_id', ''), _negated=True), fields=('player', 'source', 'external_id'), name='unique_external_calendar_event'),
        ),
    ]
