# Generated by Django 5.2.12 on 2026-05-07 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0050_lantern'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lantern',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='lanterndelivery',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddConstraint(
            model_name='habit',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('player', 'name'), name='unique_active_habit_name_per_player'),
        ),
    ]
