# Generated by Django 4.2 on 2026-05-08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0051_habit_unique_active_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='magiclinktoken',
            name='otp_code',
            field=models.CharField(
                blank=True,
                help_text='メール認証用の6桁数字。MagicLinkRequestView で自動生成。',
                max_length=6,
                verbose_name='6桁OTPコード',
            ),
        ),
    ]
