# Generated by Django 5.2.12 on 2026-05-10 04:59

from django.db import migrations, models


def create_new_stats_for_existing_players(apps, schema_editor):
    """FEAT-171: 既存プレイヤー全員に創造力・貢献力の CharacterStat を作成する。"""
    CharacterStat = apps.get_model('api', 'CharacterStat')
    PlayerProfile = apps.get_model('api', 'PlayerProfile')

    new_stat_names = ['創造力', '貢献力']

    for player in PlayerProfile.objects.all():
        for stat_name in new_stat_names:
            CharacterStat.objects.get_or_create(
                player=player,
                name=stat_name,
                defaults={
                    'level':       1,
                    'current_exp': 0,
                    'max_exp':     100,
                },
            )


def remove_new_stats(apps, schema_editor):
    """ロールバック用: 創造力・貢献力の CharacterStat を削除する。"""
    CharacterStat = apps.get_model('api', 'CharacterStat')
    CharacterStat.objects.filter(name__in=['創造力', '貢献力']).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0055_playerprofile_last_fruit_distribution'),
    ]

    operations = [
        # ① STAT_CHOICES の choices フィールドを更新（Django が自動生成した AlterField）
        migrations.AlterField(
            model_name='characterstat',
            name='name',
            field=models.CharField(choices=[('運動力', '運動力'), ('学習力', '学習力'), ('精神力', '精神力'), ('健康力', '健康力'), ('創造力', '創造力'), ('貢献力', '貢献力')], max_length=20, verbose_name='ステータス名'),
        ),
        migrations.AlterField(
            model_name='timelineevent',
            name='category',
            field=models.CharField(choices=[('study', '学習'), ('business', '仕事'), ('exercise', '運動'), ('fitness', '体力'), ('beauty', '美容'), ('health', '健康'), ('mental', '精神'), ('creative', '創造'), ('social', '社交'), ('rest', '休息'), ('other', 'その他'), ('habit', '習慣'), ('work', '仕事（旧）')], default='other', max_length=20, verbose_name='カテゴリ'),
        ),
        # ② 既存プレイヤーへのデータ付与（FEAT-171）
        migrations.RunPython(
            create_new_stats_for_existing_players,
            reverse_code=remove_new_stats,
        ),
    ]
