# Generated by Django 5.2.12 on 2026-05-10 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0056_alter_characterstat_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerprofile',
            name='last_achievement_check_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='最終実績チェック日時'),
        ),
    ]
