# Generated by Django 5.2.12 on 2026-05-13 08:45

import api.models.auth
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0062_character_key_to_flutter_alignment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default=api.models.auth._generate_guest_token, max_length=64, unique=True, verbose_name='ゲストトークン')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('last_active_at', models.DateTimeField(auto_now=True, verbose_name='最終アクティブ')),
                ('player_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='guest_session', to='api.playerprofile', verbose_name='プレイヤープロフィール')),
            ],
            options={
                'verbose_name': 'ゲストセッション',
                'verbose_name_plural': 'ゲストセッション',
            },
        ),
        migrations.CreateModel(
            name='GuestPromotePending',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default=api.models.auth._generate_guest_token, max_length=64, unique=True, verbose_name='確認トークン')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(verbose_name='有効期限')),
                ('target_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guest_promote_pendings', to=settings.AUTH_USER_MODEL, verbose_name='切替先ユーザー')),
                ('guest_session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='promote_pending', to='api.guestsession', verbose_name='ゲストセッション')),
            ],
            options={
                'verbose_name': 'ゲスト昇格確認保留',
                'verbose_name_plural': 'ゲスト昇格確認保留',
            },
        ),
        migrations.AddIndex(
            model_name='guestsession',
            index=models.Index(fields=['last_active_at'], name='api_guestse_last_ac_62ca7a_idx'),
        ),
    ]
