# Generated by Django 5.2.12 on 2026-05-15 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0066_expand_habit_and_timeline_category_to_11'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='questcompletion',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='questcompletion',
            name='player',
        ),
        migrations.DeleteModel(
            name='Quest',
        ),
        migrations.DeleteModel(
            name='QuestCompletion',
        ),
    ]
