# Generated by Django 5.2.12 on 2026-05-18 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0068_rename_gacha_addiction_achievement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerprofile',
            name='gender',
            field=models.CharField(choices=[('m', '男性'), ('f', '女性'), ('n', '回答しない')], default='f', max_length=1, verbose_name='性別'),
        ),
    ]
