# Generated by Django 5.2.12 on 2026-05-18 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0069_alter_playerprofile_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habit',
            name='due_time',
        ),
    ]
