# Generated by Django 5.2.12 on 2026-05-19 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0070_remove_habit_due_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='timelineevent',
            name='google_event_id',
            field=models.CharField(blank=True, db_index=True, help_text='Sabiowl → Google push 時の Google 側イベント ID（双方向追随用）', max_length=128, null=True, verbose_name='Google Event ID'),
        ),
    ]
