# Generated by Django 5.2.12 on 2026-05-23 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0080_remove_quest_notif_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enemy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text="識別子 'goblin' / 'orc' 等", max_length=32, unique=True)),
                ('name', models.CharField(help_text='表示名「ゴブリン」等', max_length=64)),
                ('sprite_key', models.CharField(help_text='Flutter 側 assets/images/battle/<key>.png', max_length=64)),
                ('base_hp', models.IntegerField(default=100)),
                ('base_atk', models.IntegerField(default=10)),
                ('base_spd', models.IntegerField(default=10, help_text='ATB 充填速度')),
                ('level_scaling', models.FloatField(default=1.0, help_text='Player.level に比例 (1.0 = 等倍)')),
                ('reward_coins', models.IntegerField(default=10)),
                ('reward_exp', models.IntegerField(default=20)),
                ('tier', models.CharField(choices=[('zako', '雑魚'), ('boss', 'ボス')], default='zako', max_length=16)),
            ],
            options={
                'verbose_name': '敵マスタ',
                'verbose_name_plural': '敵マスタ',
            },
        ),
        migrations.CreateModel(
            name='WeaponMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=64)),
                ('atk_bonus', models.IntegerField(default=10)),
                ('description', models.CharField(blank=True, default='', max_length=128)),
            ],
            options={
                'verbose_name': '武器マスタ',
                'verbose_name_plural': '武器マスタ',
            },
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='battle_charges',
            field=models.IntegerField(default=0, help_text='FEAT-295: バトル出陣チケット (習慣達成で +1、3 で出陣可能、上限 9)'),
        ),
        migrations.AlterField(
            model_name='playerprofile',
            name='timeline_uncompleted_reminder_enabled',
            field=models.BooleanField(default=False, help_text='FEAT-273: タイムライン予定の開始時刻 +15 分後に未完了なら通知でリマインドする。デフォルト False、マイページのトグルで個別 ON。Flutter local notifications で実装、Backend スケジューラーは不要。'),
        ),
        migrations.CreateModel(
            name='Battle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enemy_hp_init', models.IntegerField(help_text='戦闘開始時の敵 HP (player.level * level_scaling 適用済)')),
                ('enemy_atk_init', models.IntegerField()),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('result', models.CharField(blank=True, choices=[('win', '勝利'), ('lose', '敗北'), ('abandon', '中断')], max_length=16, null=True)),
                ('token', models.CharField(db_index=True, help_text='/finish/ 検証用、32 文字ランダム + 30 分期限', max_length=64, unique=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battles', to='api.playerprofile')),
                ('enemy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.enemy')),
            ],
            options={
                'verbose_name': '戦闘セッション',
                'verbose_name_plural': '戦闘セッション',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='BattleLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary_text', models.TextField(help_text='Flutter 側で生成 (例: "サビ 通常攻撃 → ゴブリン -15HP\\n...")')),
                ('total_damage_dealt', models.IntegerField(default=0)),
                ('total_damage_taken', models.IntegerField(default=0)),
                ('rounds', models.IntegerField(default=0)),
                ('rewards_coins', models.IntegerField(default=0)),
                ('rewards_exp', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('battle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='log', to='api.battle')),
            ],
            options={
                'verbose_name': '戦闘ログ',
                'verbose_name_plural': '戦闘ログ',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlayerWeapon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_equipped', models.BooleanField(default=True, help_text='MVP は 1 人 1 武器のため通常 True、Phase 2 で複数所持に拡張')),
                ('acquired_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weapons', to='api.playerprofile')),
                ('weapon', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.weaponmaster')),
            ],
            options={
                'verbose_name': 'プレイヤー武器',
                'verbose_name_plural': 'プレイヤー武器',
                'constraints': [models.UniqueConstraint(fields=('player', 'weapon'), name='unique_player_weapon')],
            },
        ),
    ]
