# Generated by Django 5.2.12 on 2026-05-24 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0083_guild_enemies_seed'),
    ]

    operations = [
        migrations.AddField(
            model_name='battle',
            name='potions_planned',
            field=models.IntegerField(default=0, help_text='FEAT-298: 戦闘開始前に設定された回復薬使用予定数 (0-3)'),
        ),
        migrations.AddField(
            model_name='battle',
            name='potions_used',
            field=models.IntegerField(default=0, help_text='FEAT-298: 戦闘中に実際に使用された回復薬数 (履歴)'),
        ),
    ]
