# Generated by Django 5.2.12 on 2026-05-25 00:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0084_battle_potion_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(help_text="'warrior' / 'mage' / 'thief' / 'cleric' / 'berserker'", max_length=32, unique=True)),
                ('job_name', models.CharField(help_text='表示名「戦士」等', max_length=64)),
                ('atb_speed_modifier', models.FloatField(default=1.0, help_text='ATB ゲージ充填速度倍率 (0.6=狂戦士 / 1.5=盗賊)')),
                ('attack_power_modifier', models.FloatField(default=1.0, help_text='攻撃力倍率 (0.7=僧侶 / 1.6=狂戦士)')),
                ('on_hit_effect', models.CharField(choices=[('none', '効果なし'), ('burn', '炎ダメージ (DoT 風)'), ('heal', 'HP 吸収')], default='none', help_text='攻撃時の追加効果 (none/burn/heal)', max_length=32)),
                ('ult_cost', models.IntegerField(default=3, help_text='大技解放に必要なゲージ満タン保留回数 (1=狂戦士 / 4=盗賊)')),
                ('description', models.CharField(blank=True, default='', help_text='UI 表示用説明（一行）', max_length=200)),
            ],
            options={
                'verbose_name': 'ジョブマスタ',
                'verbose_name_plural': 'ジョブマスタ',
            },
        ),
        migrations.AddField(
            model_name='character',
            name='job',
            field=models.ForeignKey(blank=True, help_text='FEAT-299: ジョブ駆動設計の修飾子源。null なら Backend が warrior フォールバック', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='characters', to='api.job', verbose_name='ジョブ'),
        ),
    ]
