# Generated by Django 5.2.12 on 2026-05-25 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0086_job_seed'),
    ]

    operations = [
        migrations.AddField(
            model_name='enemy',
            name='magical_resistance',
            field=models.FloatField(default=1.0, help_text='FEAT-302: 魔法攻撃 (burn / heal) 効果倍率 (default 1.0)'),
        ),
        migrations.AddField(
            model_name='enemy',
            name='physical_resistance',
            field=models.FloatField(default=1.0, help_text='FEAT-302: 物理攻撃ダメージ倍率 (1.0=等倍 / 0.7=30%軽減 / 1.3=30%増幅)'),
        ),
        migrations.AddField(
            model_name='enemy',
            name='unlock_level',
            field=models.IntegerField(default=0, help_text='FEAT-302: 解禁プレイヤーレベル (0=常時解禁 / 15=mid_boss / 25=boss / 35=hidden_boss)'),
        ),
        migrations.AddField(
            model_name='enemy',
            name='weak_ult_cost',
            field=models.IntegerField(blank=True, default=None, help_text='FEAT-302: 弱点 ult_cost (null=弱点なし / 例: 4 で thief 限定で +30%)', null=True),
        ),
        migrations.AlterField(
            model_name='enemy',
            name='tier',
            field=models.CharField(choices=[('zako', '雑魚'), ('mid_boss', '中ボス'), ('boss', 'ボス'), ('hidden_boss', '隠しボス')], default='zako', max_length=16),
        ),
    ]
