# Generated by Django 5.2.12 on 2026-05-25 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0088_seed_3_new_enemies'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerprofile',
            name='active_job',
            field=models.ForeignKey(blank=True, help_text='FEAT-304: プレイヤーが選択したジョブ (null=初期ジョブ active_character.job を使用)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='players_using', to='api.job', verbose_name='アクティブジョブ'),
        ),
    ]
