# Generated by Django 5.2.12 on 2026-05-26 11:21
# 【FEAT-314】ダイヤ取得経路追加用フィールド + 既存 PlayerAchievement 過去遡及付与回避バックフィル。

from django.db import migrations, models


def _backfill_existing_diamond_awarded(apps, schema_editor):
    """既存の PlayerAchievement (リリース前の既存ユーザー) に対して
    `diamond_awarded=True` を強制設定 (= 過去遡及付与しない方針、Pre-mortem #2)。

    新規 unlock (本 FEAT 適用後) のみ +20 ダイヤを付与する経路にする。
    既存 unlock 済 N 件 × 20 ダイヤを一斉に配ると経済バランス破壊するため明示禁止。
    """
    PlayerAchievement = apps.get_model('api', 'PlayerAchievement')
    updated = PlayerAchievement.objects.filter(diamond_awarded=False).update(
        diamond_awarded=True,
    )
    print(f'[migration 0091] Backfilled diamond_awarded=True for {updated} '
          f'existing PlayerAchievement rows (過去遡及付与を回避、'
          'リリース後の新規 unlock のみ +20 対象化)')


def _revert_backfill(apps, schema_editor):
    """rollback: backfill 自体は冪等なので no-op で十分 (元の False に戻したい
    場合は手動でクエリ実行、自動 revert は副作用が大きすぎるため空)。"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0090_add_weekly_character_rewards'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerachievement',
            name='diamond_awarded',
            field=models.BooleanField(default=False, help_text='FEAT-314: unlock 時の祝福 +20 ダイヤ付与済フラグ (claim 経路とは別軸)', verbose_name='称号獲得 +20 ダイヤ付与済'),
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='last_battle_diamond_at',
            field=models.DateField(blank=True, help_text='FEAT-314: その日初のバトル勝利でダイヤ+5、当日付与済みなら null 以外で冪等担保', null=True, verbose_name='最終バトル勝利ダイヤ付与日'),
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='last_streak_diamond_day',
            field=models.IntegerField(default=0, help_text='FEAT-314: 7 の倍数達成でダイヤ+5、付与済み streak 値以下では再付与しない', verbose_name='最終ストリークダイヤ付与 streak 日'),
        ),
        # 【FEAT-314 Pre-mortem #2】既存 PlayerAchievement に過去遡及付与しないよう
        # `diamond_awarded=True` を強制 backfill (ダイヤインフレ回避)。
        migrations.RunPython(_backfill_existing_diamond_awarded, _revert_backfill),
    ]
