# Generated by Django 5.2.12 on 2026-05-27 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0093_weapon_seed'),
    ]

    operations = [
        migrations.AddField(
            model_name='gachareward',
            name='weapon_key',
            field=models.CharField(blank=True, default='', help_text='reward_type="weapon" のとき WeaponMaster.key を保持', max_length=32, verbose_name='武器キー (FEAT-326)'),
        ),
        migrations.AlterField(
            model_name='gachareward',
            name='reward_type',
            field=models.CharField(choices=[('exp', '経験値'), ('diamond', 'ダイヤ'), ('xp_boost', 'XPブースト'), ('title', '称号'), ('character', 'キャラクター'), ('weapon', '武器')], max_length=20, verbose_name='報酬種別'),
        ),
    ]
