# Generated by Django 5.2.12 on 2026-07-09
#
# 【2026-07-09】Django が検知した既存 model の drift を回収する no-op / safe 系
# migration。0182_playerstats_matrix_proxy と経路を分けることで、機能追加と
# 既存 model の技術的整理を混同しないようにする。
#
# 内訳:
#   1. RenameIndex × 4 (iapreceipt / playerannouncementread の index 名変更)
#      Django の index name hash が変更されたことによる bookkeeping 更新。
#      PostgreSQL: ALTER INDEX ... RENAME TO ... = 即座、ロックなし、
#      indexed columns の構造は不変。
#
#   2. AlterField id (AutoField → BigAutoField) × 5
#      (announcement / iapreceipt / maintenanceconfig / playerannouncementread /
#       tasksuggestion)
#      DEFAULT_AUTO_FIELD 設定変更の drift capture。PostgreSQL の
#      ALTER COLUMN id TYPE bigint は table を rewrite する潜在リスクあり。
#      対象 5 model はいずれもリリース初期の row 数が小さい (数十〜数千):
#         announcement / maintenanceconfig / tasksuggestion  : master data 系、~30 行
#         playerannouncementread  : ユーザー数 × お知らせ数、~千行
#         iapreceipt              : 課金件数、初期は数十〜数百
#      いずれも即時完了想定。ただし本 migration 実行時のみ短時間の table
#      lock が発生する可能性があるため、prod は maintenance window 中に実行推奨。
#
#   3. AlterField active_job (playerprofile) の help_text 更新
#      Python-side のみの変更、DB 影響ゼロ。
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0180_remove_tutorial_image'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='iapreceipt',
            new_name='api_iaprece_player__5776c3_idx',
            old_name='api_iaprece_player__93f0e7_idx',
        ),
        migrations.RenameIndex(
            model_name='iapreceipt',
            new_name='api_iaprece_event_i_2d8eec_idx',
            old_name='api_iaprece_event_i_94d09c_idx',
        ),
        migrations.RenameIndex(
            model_name='iapreceipt',
            new_name='api_iaprece_status_27e26a_idx',
            old_name='api_iaprece_status_4d0fb1_idx',
        ),
        migrations.RenameIndex(
            model_name='playerannouncementread',
            new_name='api_playera_player__daef01_idx',
            old_name='api_playera_player__d3ec23_idx',
        ),
        migrations.AlterField(
            model_name='announcement',
            name='id',
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name='ID',
            ),
        ),
        migrations.AlterField(
            model_name='iapreceipt',
            name='id',
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name='ID',
            ),
        ),
        migrations.AlterField(
            model_name='maintenanceconfig',
            name='id',
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name='ID',
            ),
        ),
        migrations.AlterField(
            model_name='playerannouncementread',
            name='id',
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name='ID',
            ),
        ),
        migrations.AlterField(
            model_name='playerprofile',
            name='active_job',
            field=models.ForeignKey(
                blank=True,
                help_text='FEAT-430 で v1.0 deactivate (battle.py 未参照)。'
                          'v1.1+ 熟練度システムで再活用予定。',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='players_using',
                to='api.job',
                verbose_name='アクティブジョブ',
            ),
        ),
        migrations.AlterField(
            model_name='tasksuggestion',
            name='id',
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name='ID',
            ),
        ),
    ]
