# Generated by Django 5.2.12 on 2026-07-09
#
# 【2026-07-09】admin 画面刷新の 2 段構え。
#
#   1. CreateModel PlayerStatsMatrix (proxy=True)
#      PlayerProfile を「プレイヤーステータス概観」として admin に登録するための
#      proxy model。DB スキーマ変更ゼロ (proxy=True は Python-only、Django の
#      内部 registry と admin ルーティングのためだけに migration が必要)。
#
#   2. AlterModelOptions characterstat
#      verbose_name 「キャラクターステータス」→「ステータス個別編集」に変更。
#      「キャラ」が Character (Sabi 等 8 キャラ) と混同されやすい問題の解消 +
#      long-format admin の位置付けを「個別編集導線」と明示する。
#      DB 影響ゼロ (verbose_name は admin/UI 用の label のみ)。
#
# admin.py 側で PlayerStatsMatrixAdmin (pivot ビュー、1 行 = 1 プレイヤー、
# 6 ステータス列 + 合計列) を新規登録する。
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0181_field_drift_capture'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerStatsMatrix',
            fields=[
            ],
            options={
                'verbose_name': 'プレイヤーステータス',
                'verbose_name_plural': 'プレイヤーステータス',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('api.playerprofile',),
        ),
        migrations.AlterModelOptions(
            name='characterstat',
            options={
                'verbose_name': 'ステータス個別編集',
                'verbose_name_plural': 'ステータス個別編集',
            },
        ),
    ]
