# Generated by Django 5.2.12 on 2026-07-09
#
# 【FEAT-490 (2026-07-09)】Gift を「XP ブースト + コイン + バトルチャージ」の
# 3 種セットに拡張。Gift モデルに coins_awarded / charges_awarded 2 field 追加。
#
# 【意味論】default=0 は 2 通りの意味を持つ:
#   1. 旧 gift レコード (FEAT-451 前後の XP boost / diamond only 経路) の residual
#      → 経路が存在しなかったので 0 は「実際に付与していない」の意味で正しい
#   2. 新 gift レコードで cap (3 senders/日) 到達で受け取れなかった場合の記録
#
# 破壊的マイグレーションではない (AddField default=0)、prod safe。
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0182_playerstats_matrix_proxy'),
    ]

    operations = [
        migrations.AddField(
            model_name='gift',
            name='charges_awarded',
            field=models.IntegerField(default=0, verbose_name='付与バトルチャージ (cap 到達時 0)'),
        ),
        migrations.AddField(
            model_name='gift',
            name='coins_awarded',
            field=models.IntegerField(default=0, verbose_name='付与コイン (cap 到達時 0)'),
        ),
    ]
