# Generated by Django 5.2.12 on 2026-07-30 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0189_free_memo_deleted_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerJobMastery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(default=1, verbose_name='熟練度レベル (1-10)')),
                ('exp', models.IntegerField(default=0, verbose_name='熟練度 EXP (current level 内)')),
                ('is_maxed', models.BooleanField(default=False, verbose_name='Max 到達済')),
                ('first_maxed_at', models.DateTimeField(blank=True, null=True, verbose_name='Max 到達日時')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='masteries_by_player', to='api.job')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_masteries', to='api.playerprofile')),
            ],
            options={
                'verbose_name': 'ジョブ熟練度',
                'verbose_name_plural': 'ジョブ熟練度',
                'indexes': [models.Index(fields=['player', 'is_maxed'], name='idx_player_job_mastery_maxed')],
                'constraints': [models.UniqueConstraint(fields=('player', 'job'), name='unique_player_job_mastery')],
            },
        ),
    ]
