"""【FEAT-516 (2026-08-04)】i18n 対象から漏れていた 7 model / 13 field に `_en` を追加。

## 経緯

ユーザー報告は **1 行**だった —— 「チャレンジ画面の説明文が英語にならない」。
調べたところ、同じ状態の field が他に 12 個あった。

FEAT-489 Phase 4 は対象を「5 model」と**手で数えて**決めており、
数えたリストは数えた人が思い出したものしか含まなかった。
`api/i18n_targets.py` の自動列挙は「`_en` を **持っている** model」を発見する
仕組みで、**`_en` が無い model は構造的に見つけられない**。今回の漏れはその盲点。

再発防止として `api/tests/test_i18n_field_census.py` を追加した。
「運営が書く文言 field には `_en` がある」をソース走査で縛るので、
**次に誰かが表示用 field を足した瞬間に CI が落ちる**。

## 対象

| model | field | ユーザーに見える場所 |
|---|---|---|
| Achievement | name / description | 実績画面 |
| WeaponMaster | name / description | 武器ドロップ toast / ショップ |
| GachaReward | name / detail | ガチャ結果 |
| Job | description | キャラ詳細 (`job_name_en` だけ先に追加され description が漏れていた) |
| PuzzleWorldScene | name / tagline | シーン選択 / 詳細 |
| Challenge | title / description | チャレンジカード / 詳細ダイアログ |
| MaintenanceConfig | title / body | メンテナンス overlay |

`Challenge` と `MaintenanceConfig` は admin が運用中に作るので現在 0 行。
**「0 行だから後回し」にはしない** —— メンテナンス告知が英語ユーザーに
日本語で出るのが最悪のタイミングになる。行が無いので投入コストはゼロ。

## data migration は無い

`_en` は空で作り、翻訳は `translate_master_data` コマンドで投入する
(`doc/i18n/master_data_en.json`)。既存行への影響はゼロ。
"""
# Generated by Django 6.0.5 on 2026-08-04 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0199_purge_dead_title_rewards'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='description_en',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='実績説明(英語版)'),
        ),
        migrations.AddField(
            model_name='achievement',
            name='name_en',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='実績名(英語版)'),
        ),
        migrations.AddField(
            model_name='challenge',
            name='description_en',
            field=models.TextField(blank=True, default='', verbose_name='説明文(英語版)'),
        ),
        migrations.AddField(
            model_name='challenge',
            name='title_en',
            field=models.CharField(blank=True, default='', max_length=80, verbose_name='タイトル(英語版)'),
        ),
        migrations.AddField(
            model_name='gachareward',
            name='detail_en',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='報酬詳細(英語版)'),
        ),
        migrations.AddField(
            model_name='gachareward',
            name='name_en',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='報酬名(英語版)'),
        ),
        migrations.AddField(
            model_name='job',
            name='description_en',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='ジョブ説明(英語版)'),
        ),
        migrations.AddField(
            model_name='maintenanceconfig',
            name='body_en',
            field=models.TextField(blank=True, default='', verbose_name='本文(英語版)'),
        ),
        migrations.AddField(
            model_name='maintenanceconfig',
            name='title_en',
            field=models.CharField(blank=True, default='', max_length=60, verbose_name='タイトル(英語版)'),
        ),
        migrations.AddField(
            model_name='puzzleworldscene',
            name='name_en',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='シーン名(英語版)'),
        ),
        migrations.AddField(
            model_name='puzzleworldscene',
            name='tagline_en',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='キャッチコピー(英語版)'),
        ),
        migrations.AddField(
            model_name='weaponmaster',
            name='description_en',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='武器説明(英語版)'),
        ),
        migrations.AddField(
            model_name='weaponmaster',
            name='name_en',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='武器名(英語版)'),
        ),
    ]
