# Generated by Django 6.0.8 on 2026-09-05
#
# 【FEAT-539 (2026-09-05)】その日の初回タスク達成で「連続日数 (累計日数)」を出す。
#
# ⚠️ **スキーマ追加のみ。`RunPython` は意図的に書いていない** (指示書 Phase 1)。
#    既存ユーザーのデータ投入は `manage.py backfill_daily_achievements --apply` が
#    行う (CLAUDE.md「破壊的データマイグレーション禁止」/ FEAT-250)。
#    migration に投入を書くと、Render の build.sh が全ユーザー分の走査を
#    デプロイのたびに抱えることになり、失敗時に切り戻せない。
#
# ⚠️ `best_task_streak_days` は v1.1.2 では **表示しない**が、Phase 2 で
#    **書き込みはする**。migration を 2 度切らないために今入れている (決定 4)。

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0202_bug146_noon_castle_town_tagline'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerstreakstate',
            name='best_task_streak_days',
            field=models.IntegerField(default=0, verbose_name='最長連続達成日数'),
        ),
        migrations.CreateModel(
            name='DailyAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='達成日')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_achievements', to='api.playerprofile', verbose_name='プレイヤー')),
            ],
            options={
                'verbose_name': '日次達成記録',
                'verbose_name_plural': '日次達成記録',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['player', '-date'], name='api_dailyac_player__1be871_idx')],
                'constraints': [models.UniqueConstraint(fields=('player', 'date'), name='unique_player_daily_achievement')],
            },
        ),
    ]
