# Generated by Django 6.0.8 on 2026-09-06
#
# 【BUG-153 (2026-09-06)】`ChallengeParticipation` の model に verbose_name が
# 無く、admin の削除確認画面に **`challenge participation`** と英語で出ていた。
#
# ⚠️ `AlterModelOptions` は **スキーマを一切触らない** (Django の state だけを
#    動かす)。テーブルにも索引にも DDL は流れないので、prod への適用は無害。
# ⚠️ それでも migration は生まれるので、**コミットに含めること**。
#    含め忘れると CI の `makemigrations --check` が落ちる。

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0203_feat539_daily_achievement'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='challengeparticipation',
            options={'verbose_name': '月次チャレンジ参加', 'verbose_name_plural': '月次チャレンジ参加'},
        ),
    ]
