# Generated by Django 6.0.8 on 2026-09-06 08:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0204_bug153_challenge_participation_verbose_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountSuspensionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('suspend', '停止'), ('lift', '解除')], max_length=10, verbose_name='操作')),
                ('reason', models.TextField(blank=True, default='', help_text='ユーザーの画面には表示されません。解除判断と問い合わせ回答のための記録です。', verbose_name='理由 (運営内部用)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='日時')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='実行者')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suspension_logs', to=settings.AUTH_USER_MODEL, verbose_name='対象ユーザー')),
            ],
            options={
                'verbose_name': 'アカウント停止履歴',
                'verbose_name_plural': 'アカウント停止履歴',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='api_account_user_id_1d1825_idx')],
            },
        ),
    ]
