# Generated by Django 6.0.8 on 2026-09-23 02:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0205_feat541_account_suspension_log'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppUpdateConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=False, help_text='OFF のあいだは何も出ません。事故ったらここを OFF にすれば 60 秒で全ユーザーから消えます。', verbose_name='更新告知を有効にする')),
                ('latest_version', models.CharField(blank=True, default='', help_text='端末がこれより古ければ「後で」を押せる告知を出します (例: 1.1.4)。⚠️ 上げるのは、実機でストアから実際に落とせることを確認した後にしてください。', max_length=20, verbose_name='最新バージョン (推奨更新のしきい値)')),
                ('min_supported_version', models.CharField(blank=True, default='', help_text='端末がこれより古ければ「後で」を押せない告知を出します。⚠️ 空のままが既定です。入れるのは「その版ではデータが壊れる」ときだけ。審査中の版を含めないでください (reviewer が古い版で詰みます)。', max_length=20, verbose_name='最低サポートバージョン (必須更新のしきい値)')),
                ('title', models.CharField(blank=True, default='新しい Sabiowl をご用意しました', max_length=60, verbose_name='タイトル (推奨更新)')),
                ('title_en', models.CharField(blank=True, default='', max_length=60, verbose_name='タイトル(英語版)')),
                ('body', models.TextField(blank=True, default='App Store から更新していただけます。お急ぎでなくとも構いません。あなたが積み上げてきた記録は、そのまま引き継がれますのでご安心ください 🪶', max_length=400, verbose_name='本文 (推奨更新、サビ口調)')),
                ('body_en', models.TextField(blank=True, default='', verbose_name='本文(英語版)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='app_update_changes', to=settings.AUTH_USER_MODEL, verbose_name='最終更新者')),
            ],
            options={
                'verbose_name': 'バージョンアップ告知設定',
                'verbose_name_plural': 'バージョンアップ告知設定',
            },
        ),
    ]
