# Generated by Django 6.0.8 on 2026-09-23 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0206_feat543_app_update_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='appupdateconfig',
            name='mandatory_body',
            field=models.TextField(blank=True, default='今のバージョンでは、正しくご利用いただけない状態です。App Store から更新してください。あなたの記録は残っておりますので、更新後もそのままお使いいただけます', max_length=400, verbose_name='本文 (必須更新)'),
        ),
        migrations.AddField(
            model_name='appupdateconfig',
            name='mandatory_body_en',
            field=models.TextField(blank=True, default='This version can no longer run correctly. Please update from the App Store. All of your records are safe and will be waiting for you.', verbose_name='本文(英語版・必須更新)'),
        ),
        migrations.AddField(
            model_name='appupdateconfig',
            name='mandatory_title',
            field=models.CharField(blank=True, default='更新をお願いいたします', max_length=60, verbose_name='タイトル (必須更新)'),
        ),
        migrations.AddField(
            model_name='appupdateconfig',
            name='mandatory_title_en',
            field=models.CharField(blank=True, default='An update is required to continue', max_length=60, verbose_name='タイトル(英語版・必須更新)'),
        ),
        migrations.AlterField(
            model_name='appupdateconfig',
            name='body',
            field=models.TextField(blank=True, default='App Store からバージョン更新をお願いします', max_length=400, verbose_name='本文 (推奨更新、サビ口調)'),
        ),
        migrations.AlterField(
            model_name='appupdateconfig',
            name='body_en',
            field=models.TextField(blank=True, default='You can update the app from the App Store.', verbose_name='本文(英語版)'),
        ),
        migrations.AlterField(
            model_name='appupdateconfig',
            name='title',
            field=models.CharField(blank=True, default='新しいバージョンが届いています', max_length=60, verbose_name='タイトル (推奨更新)'),
        ),
        migrations.AlterField(
            model_name='appupdateconfig',
            name='title_en',
            field=models.CharField(blank=True, default='A new version is available.', max_length=60, verbose_name='タイトル(英語版)'),
        ),
    ]
